# Brand & Identity
brand_name: "Acme Modular"
brand_domain: "acmemodular.com"
logo_url: "https://example.com/acme-logo.png"
header_title: "Acme AI‑Powered LLM Search Visibility Tool"
header_subtitle: "Enhanced Analytics & Competitive Intelligence"
header_byline_html: "Created by <a href='https://example.com' target='_blank' style='color:#666;'>Your Agency</a>"


# UI Palette
palette:
primary: "#667eea"
secondary: "#764ba2"
hover: "#e53935" # tab hover color
text_on_primary: "#ffffff"
text_default: "#000000"


# Competitors (case-insensitive exact word matches; add aliases if needed)
competitors:
- ROXBOX
- Wilmot
- Pac-Van
- BMarko
- Giant
- XCaliber
- Conexwest
- Mobile Modular
- WillScot


# Optional competitor alias regexes (advanced)
# Examples: map brand to one or more regex patterns (OR | allowed)
competitor_aliases: {}
# WillScot: "WillScot|Williams\s+Scotsman"


# Query Templates (per category)
query_templates:
Product Discovery:
- "What companies provide modular container offices in the US?"
- "Best portable office solutions for construction sites"
- "Mobile office rental companies near me"
- "Temporary office buildings for sale"
- "Modular construction office trailers"
Brand Comparison:
- "Compare modular office companies"
- "Best alternative to Mobile Modular offices"
- "Pac-Van competitors for portable buildings"
Solution Seeking:
- "How to set up temporary office space on job site"
- "Portable office rental vs purchase decision"
- "Custom modular office building design"
Industry Specific:
- "Construction site office trailer requirements"
- "Healthcare modular building solutions"
- "School portable classroom alternatives"
Technical Queries:
- "Modular office building specifications"
- "Portable office electrical requirements"
- "ADA compliant modular buildings"


# KPI thresholds (used for recommendations/flags)
thresholds:
mention_rate_warn: 50
first_third_warn: 30
positive_context_warn: 60
nonbranded_mention_warn: 20
competitor_density_warn: 3


# Default Models
models:
openai: "gpt-4o"
gemini: "gemini-2.5-flash"
perplexity: "sonar"
